### ISSUE TITLE
Actividad 2 Infografía_Maribel Santiago Bautista 1°BS

### ISSUE THREAD

**Issue by santiagomary1004** [SistemasTecTlaxiaco/actividad-2-infografia-santiagomary1004#1]
[Actividad 2 Infografía_Maribel Santiago Bautista.pdf](https://github.com/SistemasTecTlaxiaco/actividad-2-infografia-santiagomary1004/files/9483748/Actividad.2.Infografia_Maribel.Santiago.Bautista.pdf)

**Comment by AmeliReyesHernandez** [comment]
18.8 de 20

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
